### ISSUE TITLE
cleanup/enhancement of parser

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#1823]
Things to do (PR #2177):
- [x] remove Array fallback for the transition table
This is not needed anymore since all supported engines have typed array support.
- [x] simplify transition table creation
With the transition table being a typed array the table can be prefilled with the default transition by a `.fill` call.
- [x] dont recreate arrays in `r()` everytime, instead slice from a blueprint
- [x] simplify unicode handling in `parse`
Use the new `NON_ASCII_PRINTABLE` where appropriate and restore the error state as error state.

Prolly done with next PRs:
- [x] eval read ahead in switch case (PR #2187)
The shortcuts for PRINT and CSI_PARAM are currently done before entering the switch statement, which makes them eval'd for every char that goes through the outer loop. Might be better repositioned to their own case in the switch statement.
- [x] colon notation in params state (see #2200, PR #2241)
With the true color support the parser should also get support for element notation, with is a rather big change to param state handling.
- [x] cleanup `dcsHandler` in `parse` - remove `null` type to lower branching (part of #2346)
- [x] rework fallback handler logic for parser actions
- [x] extend all parser actions with addHandler capability (#2332, PR #2346)
- [x] move all parser actions to typed array propagation (part of #2346)
- [ ] ~~optimize DCS unhook (#1909)~~ wont fix
