### ISSUE TITLE
upcoming corelib changes with the new buffer

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#1920]
Tracking issue to get outstanding core lib changes sorted:
- [x] typed array parser support (PR #1796)
- [x] apply UTF32 layout with true color support to terminal buffer (PR #1878)
- [x] cleanup intermediate `CharData` creation (part of PR #1878)
Idea is to move from the `CharData` based cell access to a more direct data access on the typed array. For convenience the `CharData` part could live on, but at least high throughput/runtime consumers (renderer and such) should be able to access the data in a faster more direct approach.
- [x] true color support (see #484, PR #1895)
This needs some tweaks/refinement of the current attribute handling and will basically introduce a second 32bit value to be carried around.
- [ ] convert string based methods in `InputHandler` into typed array (covered by #1823)
This will save forth and back conversion of charcodes needed by the parser to "speak" with the string based API.
- [ ] fix the fullwidth problems in `InputHandler` (see #1779)
- [x] eval other input encodings
In the future we might want to check, if we can gain anything from other input encodings (hottest candidate is UTF8, PR #1904).
- [ ] parser cleanup, support for colon notation (see #1823)

**Comment by jerch** [comment]
Closing this issue since most things are done. The open things are covered by other issues and will be addressed there.
