### ISSUE TITLE
revisit missing sequences

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#2358]
There are a couple of useful sequences we currently dont support and prolly should for better user experience / xterm compliance.

- [ ] DECLRMM: Analogous to DECOM with DECSTBM VT420+ supports left/right margins to restrict the cursor during normal input with DECLRMM + DECSLRM - _imho we should implement this as it makes partial screen refreshs easier for multiplexer..._
- [x] left/right scroll SL / SR (ECMA-48) Works analogous to SD / SU - _covered by #2360_
- [x] insert / remove columns DECIC / DECDC (VT420+), analogous to IL / DL - _covered by #2360_
- [ ] area functions
  Not sure about those, there are several area functions to deal with rectangular areas in a specific way. Guess this needs further eval whether we want that at all. Examples:
  - DECCARA / DECRARA
  - DECCRA
  - DECERA / DECSERA
  - DECRQCRA
  - DECFRA
  - DECEFR
  _this gets a downvote as there was not a single request for this in over 4 years, no need to complicate terminal state with ancient unused stuff_
- [ ] protection attributes
  Some of the DEC private variants like DECSED and DECSEL respect protection flags whether they can operate or not.  - _same as above, no need to complicate things with unused stuff_
- [ ] media copy (MC)
  There are actually sequences to dump buffer content in various formats, might be useful in conjunction with serialization.  - _this gets a downvote as it might reveal sensitive data to app side from other terminal sessions_
- [ ] raw key reports
  As indicated by #2357 (ff.) we might want/need a way to allow/route raw key reports to pass through. Also see https://gitlab.freedesktop.org/terminal-wg/specifications/issues/1. To get proper support in this area we might have to support DECUDK as well.  - _not yet decided..._
- [x] window manipulation (CSI .... t)
  Not all are useful for xterm.js, at least reports should work, some of the stack save/restore functions are used by multiplexers. Imho some are no-gos for xterm.js like size manipulations as it would screw up the integration. - _covered by #2393_
- [ ] new SGR modes
  Eval enhancements in SGR regarding underline with colors and line style. (Note that this is already used by some editors.) Also check for other color modes like transparent and CMYK.  - _already implemented on parser side, frontend still missing though..._
- [ ] several missing OSC commands
  Things like setting color palette entries should work. (#1493)  - _OSC 4 partially implemented in #3036, more to come..._
- [ ] last but not least: image support / SIXEL  - _WIP in #2503_

Turns out this is a pretty long wishlist, well still some time left until Xmas ~2019~, ~2020~, 2021 :smile_cat:

**Comment by jcubic** [comment]
Not sure if this belong to this issue, but I'm now working on supporting cursor movement in jQuery Terminal. I want you to look how the plot from [ervy library](https://github.com/chunqiuyiyu/ervy) looks like in xterm.js here is the output.

Xterm on Fedora

![xxx2](https://user-images.githubusercontent.com/280241/71555974-91bc7580-2a32-11ea-99d0-d7a8a1410b63.png)

and xterm.js
![xtermjs](https://user-images.githubusercontent.com/280241/71555992-d7793e00-2a32-11ea-9f8e-4b37a1aceab6.png)

(First line is correct but it didn't fit into terminal).

I use the library like in demo, but using terminal.write(plot) from ervy the same was done in node (but with console.log in above screenshot).

The ervy library have problematic 0C and 0A escape codes not sure if because of it it look like this. On real Xterm the plot looks almost correct if I removed 0[A-F] escape codes before console.log.

**Comment by jerch** [comment]
@jcubic Thx for pointing out, gonna have to look into the byte stream sent to see whats going on. Also commented on your issue here https://github.com/chunqiuyiyu/ervy/issues/13

**Comment by jerch** [comment]
@jcubic I ran the demo (includes the graph) in xterm.js and xterm and get the same output. How did you run the snippet?

**Comment by jcubic** [comment]
Just output of ervy into term.write, like in example on the website.

```javascript
      var term = new Terminal();
      term.open(document.getElementById('terminal'));
// Scatter
             const scatterData = [];

             for (let i = 1; i < 17; i++) {
                 i < 6 ? scatterData.push({ key: 'A', value: [i, i], style: ervy.fg('red', '*') })
                   : scatterData.push({ key: 'A', value: [i, 6], style: ervy.fg('red', '*') });
             }

             scatterData.push({ key: 'B', value: [2, 6], style: ervy.fg('blue', '# '), side: 2 });
             scatterData.push({ key: 'C', value: [0, 0], style: ervy.bg('cyan', 2) });

             
             var plot = ervy.scatter(scatterData, { legendGap: 18, width: 15 });

      term.write(plot);
```

**Comment by jcubic** [comment]
the ervy is from `https://terminal.jcubic.pl/js/ervy.js` converted using browserify.

**Comment by jerch** [comment]
> Just output of ervy into term.write

Ah here we go - xterm.js needs a pty in between for correct transformation, otherwise the data might be slightly off. If you run our xterm.js demo with the ervy demo it shows up correctly.

Btw I am currently trying to lift the pty burden with fake-pty as a browser shim https://github.com/jerch/browser-fakepty, but thats still in an very early stage.

**Comment by jcubic** [comment]
I thought that xterm.js require backed TTY but looking at demo it had ANSI escapes code in write so I've assume that it processes everything in browser. And with little bit of code you can write moving cursor without the backed like in this article: [Build your own Command Line with ANSI escape codes](http://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html) it would be nice if xterm.js could do that you will be able to use this in more places (like NCurses in browse).

**Comment by jerch** [comment]
Yes thats the idea behind the fake-pty. It tries to reassemble parts of common POSIX interfaces to give a more standard way to run "processes" in browsers. This would simplify porting console apps to WASM alot. Tricky part - those interfaces are oldish and awkward, and deeply woven into unix kernels.

There is a ready-to-go solution already for xterm.js: https://github.com/wavesoft/local-echo. It solves the pty issue, but is kinda hardcoded with integrated shell functionality and has no notion of termios settings, thus again would not work for RAW or ICANON mode apps out of the box.

**Comment by jerch** [comment]
Comments above were moved to #2656.

**Comment by jerch** [comment]
@Tyriar 
Made some updates to the "wishlist" above (see the italic comments on them).

**Comment by daonb** [comment]
I wanted to use mdp to display a deck and their sample display looks off (It looks good on iTerm). I believe I saw the same issue in nvim - a line printed at the start of a line where there should be a margin.

![screenshot](https://user-images.githubusercontent.com/36852/109557809-42178500-7ae1-11eb-9f36-e3401c47b83b.png)

**Comment by jerch** [comment]
@daonb I cannot repro the issue in your screenshot with Ubuntu 16 & 18 (tested with older deb package and mdp master). Which versions are you on (OS, mdp, ncurses, terminfo, xterm.js)?

To get a hold of the failing sequence it would be good if you can post a dump of the chunks being sent to the terminal containing the failing part. Not sure if DECLRMM/DECSLRM is behind this, I'd expect the lines above also being misaligned, if they were used for left indentation. But these look fine to me.

**Comment by daonb** [comment]
@jerch you're my hero, thanks!

**Comment by jerch** [comment]
Closing, as most things are dealt with or better tracked separately.
